// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0JK0nci2BJG4BuTUeOiIvhHAsBEdW4dM',
    appId: '1:680267048158:web:d5f558cd4c801eda43ce4f',
    messagingSenderId: '680267048158',
    projectId: 'zone-b3608',
    authDomain: 'zone-b3608.firebaseapp.com',
    storageBucket: 'zone-b3608.appspot.com',
    measurementId: 'G-V8VPTV3HLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUYPubcu0FT4g5aVAMQVQi5lVt2doKQc',
    appId: '1:680267048158:android:fb6c09eafd574a4043ce4f',
    messagingSenderId: '680267048158',
    projectId: 'zone-b3608',
    storageBucket: 'zone-b3608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLg8ND16VBAY0S0yAj4nQQ9_ZVUsFU1gs',
    appId: '1:680267048158:ios:0e293a715fa17ad143ce4f',
    messagingSenderId: '680267048158',
    projectId: 'zone-b3608',
    storageBucket: 'zone-b3608.appspot.com',
    iosClientId:
        '680267048158-30t91i1u7nmcqcpb4pur22nj145v49ug.apps.googleusercontent.com',
    iosBundleId: 'com.zone.appers.zone',
  );
}
